[2024-06-18T15:51:35.624+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T15:51:35.642+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T10:21:34.837213+00:00 [queued]>
[2024-06-18T15:51:35.650+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T10:21:34.837213+00:00 [queued]>
[2024-06-18T15:51:35.651+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T15:51:35.669+0530] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 10:21:34.837213+00:00
[2024-06-18T15:51:35.672+0530] {standard_task_runner.py:63} INFO - Started process 36357 to run task
[2024-06-18T15:51:35.675+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'manual__2024-06-18T10:21:34.837213+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/basic.py', '--cfg-path', '/tmp/tmpdoo4on9p']
[2024-06-18T15:51:35.676+0530] {standard_task_runner.py:91} INFO - Job 29: Subtask backup_task
[2024-06-18T15:51:35.725+0530] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task manual__2024-06-18T10:21:34.837213+00:00 [running]> on host FN-21052948.
[2024-06-18T15:51:35.799+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarika' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T10:21:34.837213+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T10:21:34.837213+00:00'
[2024-06-18T15:51:35.800+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T15:51:35.808+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T15:51:35.809+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/kiit/airflow/bashScripts/backup.sh ']
[2024-06-18T15:51:35.813+0530] {subprocess.py:86} INFO - Output:
[2024-06-18T15:51:35.819+0530] {subprocess.py:93} INFO - mysqldump: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T15:51:35.821+0530] {subprocess.py:93} INFO - mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (13) when trying to connect
[2024-06-18T15:51:35.821+0530] {subprocess.py:97} INFO - Command exited with return code 2
[2024-06-18T15:51:35.822+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T15:51:35.831+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-06-18T15:51:35.836+0530] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=backup_task, run_id=manual__2024-06-18T10:21:34.837213+00:00, execution_date=20240618T102134, start_date=20240618T102135, end_date=20240618T102135
[2024-06-18T15:51:35.851+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task backup_task (Bash command failed. The command returned a non-zero exit code 2.; 36357)
[2024-06-18T15:51:35.888+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T15:51:35.906+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T15:51:35.908+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
