[2024-06-18T16:40:00.937+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T16:40:00.951+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T11:00:00+00:00 [queued]>
[2024-06-18T16:40:00.957+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T11:00:00+00:00 [queued]>
[2024-06-18T16:40:00.957+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T16:40:00.972+0530] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 11:00:00+00:00
[2024-06-18T16:40:00.974+0530] {standard_task_runner.py:63} INFO - Started process 36967 to run task
[2024-06-18T16:40:00.976+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'scheduled__2024-06-18T11:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/basic.py', '--cfg-path', '/tmp/tmpuqiaezof']
[2024-06-18T16:40:00.977+0530] {standard_task_runner.py:91} INFO - Job 47: Subtask backup_task
[2024-06-18T16:40:01.020+0530] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T11:00:00+00:00 [running]> on host FN-21052948.
[2024-06-18T16:40:01.085+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarika' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T11:00:00+00:00'
[2024-06-18T16:40:01.086+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T16:40:01.094+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T16:40:01.094+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/kiit/airflow/bashScripts/backup.sh ']
[2024-06-18T16:40:01.099+0530] {subprocess.py:86} INFO - Output:
[2024-06-18T16:40:01.100+0530] {subprocess.py:93} INFO - /home/kiit/airflow/bashScripts/backup.sh: line 71: /home/kiit/airflow/bashscripts/delete.sh: No such file or directory
[2024-06-18T16:40:01.105+0530] {subprocess.py:93} INFO - mysql: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T16:40:01.106+0530] {subprocess.py:93} INFO - ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (13)
[2024-06-18T16:40:01.107+0530] {subprocess.py:93} INFO - (standard_in) 1: syntax error
[2024-06-18T16:40:01.110+0530] {subprocess.py:93} INFO - df: /mnt/c: Input/output error
[2024-06-18T16:40:01.111+0530] {subprocess.py:93} INFO - df: /Docker/host: Input/output error
[2024-06-18T16:40:01.113+0530] {subprocess.py:93} INFO - (standard_in) 1: syntax error
[2024-06-18T16:40:01.114+0530] {subprocess.py:93} INFO - /home/kiit/airflow/bashScripts/backup.sh: line 98: [: -eq: unary operator expected
[2024-06-18T16:40:01.114+0530] {subprocess.py:93} INFO - Backup Failed.|Required Space: GB, Available Space: 2529.39GB
[2024-06-18T16:40:01.114+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-18T16:40:01.114+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T16:40:01.138+0530] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=backup_task, run_id=scheduled__2024-06-18T11:00:00+00:00, execution_date=20240618T110000, start_date=20240618T111000, end_date=20240618T111001
[2024-06-18T16:40:01.189+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T16:40:01.209+0530] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-18T16:40:01.217+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
